[workspace]
members = ["burp", "graph-rs"]
resolver = "2"

[workspace.package]
authors = ["Jakob Sanowski <jakob.sanowski@sanbach.de>"]
categories = ["science::geo"]
edition = "2021"
keywords = ["gis", "map"]
license = "GPL-3"
repository = "https://gitlab.inf.uni-konstanz.de/jakob.sanowski/bachelor-projekt"
version = "0.1.0"
